# Combining Pokémon names and types

names = [
    'Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aerodactyl', 'Aggron', 'Aipom',
    'Alakazam', 'Alomomola', 'Altaria', 'Amaura', 'Ambipom', 'Amoonguss',
    'Ampharos', 'Anorith', 'Arbok', 'Arcanine', 'Arceus', 'Archen', 'Archeops',
    'Ariados', 'Armaldo', 'Aromatisse', 'Aron', 'Articuno', 'Audino',
    'Aurorus', 'Avalugg', 'Axew', 'Azelf', 'Azumarill', 'Azurill', 'Bagon',
    'Baltoy', 'Banette', 'Barbaracle', 'Barboach', 'Basculin', 'Bastiodon',
    'Bayleef', 'Beartic', 'Beautifly', 'Beedrill', 'Beheeyem', 'Beldum',
    'Bellossom', 'Bellsprout', 'Bergmite', 'Bibarel', 'Bidoof', 'Binacle',
    'Bisharp', 'Blastoise', 'Blaziken', 'Blissey', 'Blitzle', 'Boldore',
    'Bonsly', 'Bouffalant', 'Braixen', 'Braviary', 'Breloom', 'Bronzong',
    'Bronzor', 'Budew', 'Buizel', 'Bulbasaur', 'Buneary', 'Bunnelby', 'Burmy',
    'Butterfree', 'Cacnea', 'Cacturne', 'Camerupt', 'Carbink', 'Carnivine',
    'Carracosta', 'Carvanha', 'Cascoon', 'Castform', 'Caterpie', 'Celebi',
    'Chandelure', 'Chansey', 'Charizard', 'Charmander', 'Charmeleon', 'Chatot',
    'Cherrim', 'Cherubi', 'Chesnaught', 'Chespin', 'Chikorita', 'Chimchar',
    'Chimecho', 'Chinchou', 'Chingling', 'Cinccino', 'Clamperl', 'Clauncher',
    'Clawitzer', 'Claydol', 'Clefable', 'Clefairy', 'Cleffa', 'Cloyster',
    'Cobalion', 'Cofagrigus', 'Combee', 'Combusken', 'Conkeldurr', 'Corphish',
    'Corsola', 'Cottonee', 'Cradily', 'Cranidos', 'Crawdaunt', 'Cresselia',
    'Croagunk', 'Crobat', 'Croconaw', 'Crustle', 'Cryogonal', 'Cubchoo',
    'Cubone', 'Cyndaquil', 'Darkrai', 'DarmanitanStandard Mode',
    'DarmanitanZen Mode', 'Darumaka', 'Dedenne', 'Deerling', 'Deino',
    'Delcatty', 'Delibird', 'Delphox', 'Dewgong', 'Dewott', 'Dialga',
    'Diancie', 'Diggersby', 'Diglett', 'Ditto', 'Dodrio', 'Doduo', 'Donphan',
    'Doublade', 'Dragalge', 'Dragonair', 'Dragonite', 'Drapion', 'Dratini',
    'Drifblim', 'Drifloon', 'Drilbur', 'Drowzee', 'Druddigon', 'Ducklett',
    'Dugtrio', 'Dunsparce', 'Duosion', 'Durant', 'Dusclops', 'Dusknoir',
    'Duskull', 'Dustox', 'Dwebble', 'Eelektrik', 'Eelektross', 'Eevee',
    'Ekans', 'Electabuzz', 'Electivire', 'Electrike', 'Electrode', 'Elekid',
    'Elgyem', 'Emboar', 'Emolga', 'Empoleon', 'Entei', 'Escavalier', 'Espeon',
    'Espurr', 'Excadrill', 'Exeggcute', 'Exeggutor', 'Exploud', "Farfetch'd",
    'Fearow', 'Feebas', 'Fennekin', 'Feraligatr', 'Ferroseed', 'Ferrothorn',
    'Finneon', 'Flaaffy', 'Flabébé', 'Flareon', 'Fletchinder', 'Fletchling',
    'Floatzel', 'Floette', 'Florges', 'Flygon', 'Foongus', 'Forretress',
    'Fraxure', 'Frillish', 'Froakie', 'Frogadier', 'Froslass', 'Furfrou',
    'Furret', 'Gabite', 'Gallade', 'Galvantula', 'Garbodor', 'Garchomp',
    'Gardevoir', 'Gastly', 'Gastrodon', 'Genesect', 'Gengar', 'Geodude',
    'Gible', 'Gigalith', 'Girafarig', 'Glaceon', 'Glalie', 'Glameow', 'Gligar',
    'Gliscor', 'Gloom', 'Gogoat', 'Golbat', 'Goldeen', 'Golduck', 'Golem',
    'Golett', 'Golurk', 'Goodra', 'Goomy', 'Gorebyss', 'Gothita', 'Gothitelle',
    'Gothorita', 'Granbull', 'Graveler', 'Greninja', 'Grimer', 'Grotle',
    'Groudon', 'GroudonPrimal Groudon', 'Grovyle', 'Growlithe', 'Grumpig',
    'Gulpin', 'Gurdurr', 'Gyarados', 'Happiny', 'Hariyama', 'Haunter',
    'Hawlucha', 'Haxorus', 'Heatmor', 'Heatran', 'Heliolisk', 'Helioptile',
    'Heracross', 'Herdier', 'Hippopotas', 'Hippowdon', 'Hitmonchan',
    'Hitmonlee', 'Hitmontop', 'Ho-oh', 'Honchkrow', 'Honedge', 'Hoothoot',
    'Hoppip', 'Horsea', 'Houndoom', 'Houndour', 'Huntail', 'Hydreigon',
    'Hypno', 'Igglybuff', 'Illumise', 'Infernape', 'Inkay', 'Ivysaur',
    'Jellicent', 'Jigglypuff', 'Jirachi', 'Jolteon', 'Joltik', 'Jumpluff',
    'Jynx', 'Kabuto', 'Kabutops', 'Kadabra', 'Kakuna', 'Kangaskhan',
    'Karrablast', 'Kecleon', 'Kingdra', 'Kingler', 'Kirlia', 'Klang', 'Klefki',
    'Klink', 'Klinklang', 'Koffing', 'Krabby', 'Kricketot', 'Kricketune',
    'Krokorok', 'Krookodile', 'Kyogre', 'KyogrePrimal Kyogre', 'Kyurem',
    'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'Lairon', 'Lampent', 'Lanturn',
    'Lapras', 'Larvesta', 'Larvitar', 'Latias', 'Latios', 'Leafeon',
    'Leavanny', 'Ledian', 'Ledyba', 'Lickilicky', 'Lickitung', 'Liepard',
    'Lileep', 'Lilligant', 'Lillipup', 'Linoone', 'Litleo', 'Litwick',
    'Lombre', 'Lopunny', 'Lotad', 'Loudred', 'Lucario', 'Ludicolo', 'Lugia',
    'Lumineon', 'Lunatone', 'Luvdisc', 'Luxio', 'Luxray', 'Machamp', 'Machoke',
    'Machop', 'Magby', 'Magcargo', 'Magikarp', 'Magmar', 'Magmortar',
    'Magnemite', 'Magneton', 'Magnezone', 'Makuhita', 'Malamar', 'Mamoswine',
    'Manaphy', 'Mandibuzz', 'Manectric', 'Mankey', 'Mantine', 'Mantyke',
    'Maractus', 'Mareep', 'Marill', 'Marowak', 'Marshtomp', 'Masquerain',
    'Mawile', 'Medicham', 'Meditite', 'MeowsticFemale', 'MeowsticMale',
    'Meowth', 'Mesprit', 'Metagross', 'Metang', 'Metapod', 'Mew', 'Mewtwo',
    'Mienfoo', 'Mienshao', 'Mightyena', 'Milotic', 'Miltank', 'Mime Jr.',
    'Minccino', 'Minun', 'Misdreavus', 'Mismagius', 'Moltres', 'Monferno',
    'Mothim', 'Mr. Mime', 'Mudkip', 'Muk', 'Munchlax', 'Munna', 'Murkrow',
    'Musharna', 'Natu', 'Nidoking', 'Nidoqueen', 'Nidoran♀', 'Nidoran♂',
    'Nidorina', 'Nidorino', 'Nincada', 'Ninetales', 'Ninjask', 'Noctowl',
    'Noibat', 'Noivern', 'Nosepass', 'Numel', 'Nuzleaf', 'Octillery', 'Oddish',
    'Omanyte', 'Omastar', 'Onix', 'Oshawott', 'Pachirisu', 'Palkia',
    'Palpitoad', 'Pancham', 'Pangoro', 'Panpour', 'Pansage', 'Pansear',
    'Paras', 'Parasect', 'Patrat', 'Pawniard', 'Pelipper', 'Persian',
    'Petilil', 'Phanpy', 'Phantump', 'Phione', 'Pichu', 'Pidgeot', 'Pidgeotto',
    'Pidgey', 'Pidove', 'Pignite', 'Pikachu', 'Piloswine', 'Pineco', 'Pinsir',
    'Piplup', 'Plusle', 'Politoed', 'Poliwag', 'Poliwhirl', 'Poliwrath',
    'Ponyta', 'Poochyena', 'Porygon', 'Porygon-Z', 'Porygon2', 'Primeape',
    'Prinplup', 'Probopass', 'Psyduck', 'Pupitar', 'Purrloin', 'Purugly',
    'Pyroar', 'Quagsire', 'Quilava', 'Quilladin', 'Qwilfish', 'Raichu',
    'Raikou', 'Ralts', 'Rampardos', 'Rapidash', 'Raticate', 'Rattata',
    'Rayquaza', 'Regice', 'Regigigas', 'Regirock', 'Registeel', 'Relicanth',
    'Remoraid', 'Reshiram', 'Reuniclus', 'Rhydon', 'Rhyhorn', 'Rhyperior',
    'Riolu', 'Roggenrola', 'Roselia', 'Roserade', 'Rotom', 'RotomFan Rotom',
    'RotomFrost Rotom', 'RotomHeat Rotom', 'RotomMow Rotom', 'RotomWash Rotom',
    'Rufflet', 'Sableye', 'Salamence', 'Samurott', 'Sandile', 'Sandshrew',
    'Sandslash', 'Sawk', 'Sawsbuck', 'Scatterbug', 'Sceptile', 'Scizor',
    'Scolipede', 'Scrafty', 'Scraggy', 'Scyther', 'Seadra', 'Seaking',
    'Sealeo', 'Seedot', 'Seel', 'Seismitoad', 'Sentret', 'Serperior',
    'Servine', 'Seviper', 'Sewaddle', 'Sharpedo', 'Shedinja', 'Shelgon',
    'Shellder', 'Shellos', 'Shelmet', 'Shieldon', 'Shiftry', 'Shinx',
    'Shroomish', 'Shuckle', 'Shuppet', 'Sigilyph', 'Silcoon', 'Simipour',
    'Simisage', 'Simisear', 'Skarmory', 'Skiddo', 'Skiploom', 'Skitty',
    'Skorupi', 'Skrelp', 'Skuntank', 'Slaking', 'Slakoth', 'Sliggoo',
    'Slowbro', 'Slowking', 'Slowpoke', 'Slugma', 'Slurpuff', 'Smeargle',
    'Smoochum', 'Sneasel', 'Snivy', 'Snorlax', 'Snorunt', 'Snover', 'Snubbull',
    'Solosis', 'Solrock', 'Spearow', 'Spewpa', 'Spheal', 'Spinarak', 'Spinda',
    'Spiritomb', 'Spoink', 'Spritzee', 'Squirtle', 'Stantler', 'Staraptor',
    'Staravia', 'Starly', 'Starmie', 'Staryu', 'Steelix', 'Stoutland',
    'Stunfisk', 'Stunky', 'Sudowoodo', 'Suicune', 'Sunflora', 'Sunkern',
    'Surskit', 'Swablu', 'Swadloon', 'Swalot', 'Swampert', 'Swanna', 'Swellow',
    'Swinub', 'Swirlix', 'Swoobat', 'Sylveon', 'Taillow', 'Talonflame',
    'Tangela', 'Tangrowth', 'Tauros', 'Teddiursa', 'Tentacool', 'Tentacruel',
    'Tepig', 'Terrakion', 'Throh', 'Timburr', 'Tirtouga', 'Togekiss', 'Togepi',
    'Togetic', 'Torchic', 'Torkoal', 'Torterra', 'Totodile', 'Toxicroak',
    'Tranquill', 'Trapinch', 'Treecko', 'Trevenant', 'Tropius', 'Trubbish',
    'Turtwig', 'Tympole', 'Tynamo', 'Typhlosion', 'Tyranitar', 'Tyrantrum',
    'Tyrogue', 'Tyrunt', 'Umbreon', 'Unfezant', 'Unown', 'Ursaring', 'Uxie',
    'Vanillish', 'Vanillite', 'Vanilluxe', 'Vaporeon', 'Venipede', 'Venomoth',
    'Venonat', 'Venusaur', 'Vespiquen', 'Vibrava', 'Victini', 'Victreebel',
    'Vigoroth', 'Vileplume', 'Virizion', 'Vivillon', 'Volbeat', 'Volcanion',
    'Volcarona', 'Voltorb', 'Vullaby', 'Vulpix', 'Wailmer', 'Wailord',
    'Walrein', 'Wartortle', 'Watchog', 'Weavile', 'Weedle', 'Weepinbell',
    'Weezing', 'Whimsicott', 'Whirlipede', 'Whiscash', 'Whismur', 'Wigglytuff',
    'Wingull', 'Wobbuffet', 'Woobat', 'Wooper', 'WormadamPlant Cloak',
    'WormadamSandy Cloak', 'WormadamTrash Cloak', 'Wurmple', 'Wynaut', 'Xatu',
    'Xerneas', 'Yamask', 'Yanma', 'Yanmega', 'Yveltal', 'Zangoose', 'Zapdos',
    'Zebstrika', 'Zekrom', 'Zigzagoon', 'Zoroark', 'Zorua', 'Zubat', 'Zweilous'
]

primary_types = [
    'Grass', 'Psychic', 'Dark', 'Bug', 'Rock', 'Steel', 'Normal', 'Psychic',
    'Water', 'Dragon', 'Rock', 'Normal', 'Grass', 'Electric', 'Rock', 'Poison',
    'Fire', 'Normal', 'Rock', 'Rock', 'Bug', 'Rock', 'Fairy', 'Steel', 'Ice',
    'Normal', 'Rock', 'Ice', 'Dragon', 'Psychic', 'Water', 'Normal', 'Dragon',
    'Ground', 'Ghost', 'Rock', 'Water', 'Water', 'Rock', 'Grass', 'Ice', 'Bug',
    'Bug', 'Psychic', 'Steel', 'Grass', 'Grass', 'Ice', 'Normal', 'Normal',
    'Rock', 'Dark', 'Water', 'Fire', 'Normal', 'Electric', 'Rock', 'Rock',
    'Normal', 'Fire', 'Normal', 'Grass', 'Steel', 'Steel', 'Grass', 'Water',
    'Grass', 'Normal', 'Normal', 'Bug', 'Bug', 'Grass', 'Grass', 'Fire',
    'Rock', 'Grass', 'Water', 'Water', 'Bug', 'Normal', 'Bug', 'Psychic',
    'Ghost', 'Normal', 'Fire', 'Fire', 'Fire', 'Normal', 'Grass', 'Grass',
    'Grass', 'Grass', 'Grass', 'Fire', 'Psychic', 'Water', 'Psychic', 'Normal',
    'Water', 'Water', 'Water', 'Ground', 'Fairy', 'Fairy', 'Fairy', 'Water',
    'Steel', 'Ghost', 'Bug', 'Fire', 'Fighting', 'Water', 'Water', 'Grass',
    'Rock', 'Rock', 'Water', 'Psychic', 'Poison', 'Poison', 'Water', 'Bug',
    'Ice', 'Ice', 'Ground', 'Fire', 'Dark', 'Fire', 'Fire', 'Fire', 'Electric',
    'Normal', 'Dark', 'Normal', 'Ice', 'Fire', 'Water', 'Water', 'Steel',
    'Rock', 'Normal', 'Ground', 'Normal', 'Normal', 'Normal', 'Ground',
    'Steel', 'Poison', 'Dragon', 'Dragon', 'Poison', 'Dragon', 'Ghost',
    'Ghost', 'Ground', 'Psychic', 'Dragon', 'Water', 'Ground', 'Normal',
    'Psychic', 'Bug', 'Ghost', 'Ghost', 'Ghost', 'Bug', 'Bug', 'Electric',
    'Electric', 'Normal', 'Poison', 'Electric', 'Electric', 'Electric',
    'Electric', 'Electric', 'Psychic', 'Fire', 'Electric', 'Water', 'Fire',
    'Bug', 'Psychic', 'Psychic', 'Ground', 'Grass', 'Grass', 'Normal',
    'Normal', 'Normal', 'Water', 'Fire', 'Water', 'Grass', 'Grass', 'Water',
    'Electric', 'Fairy', 'Fire', 'Fire', 'Normal', 'Water', 'Fairy', 'Fairy',
    'Ground', 'Grass', 'Bug', 'Dragon', 'Water', 'Water', 'Water', 'Ice',
    'Normal', 'Normal', 'Dragon', 'Psychic', 'Bug', 'Poison', 'Dragon',
    'Psychic', 'Ghost', 'Water', 'Bug', 'Ghost', 'Rock', 'Dragon', 'Rock',
    'Normal', 'Ice', 'Ice', 'Normal', 'Ground', 'Ground', 'Grass', 'Grass',
    'Poison', 'Water', 'Water', 'Rock', 'Ground', 'Ground', 'Dragon', 'Dragon',
    'Water', 'Psychic', 'Psychic', 'Psychic', 'Fairy', 'Rock', 'Water',
    'Poison', 'Grass', 'Ground', 'Ground', 'Grass', 'Fire', 'Psychic',
    'Poison', 'Fighting', 'Water', 'Normal', 'Fighting', 'Ghost', 'Fighting',
    'Dragon', 'Fire', 'Fire', 'Electric', 'Electric', 'Bug', 'Normal',
    'Ground', 'Ground', 'Fighting', 'Fighting', 'Fighting', 'Fire', 'Dark',
    'Steel', 'Normal', 'Grass', 'Water', 'Dark', 'Dark', 'Water', 'Dark',
    'Psychic', 'Normal', 'Bug', 'Fire', 'Dark', 'Grass', 'Water', 'Normal',
    'Steel', 'Electric', 'Bug', 'Grass', 'Ice', 'Rock', 'Rock', 'Psychic',
    'Bug', 'Normal', 'Bug', 'Normal', 'Water', 'Water', 'Psychic', 'Steel',
    'Steel', 'Steel', 'Steel', 'Poison', 'Water', 'Bug', 'Bug', 'Ground',
    'Ground', 'Water', 'Water', 'Dragon', 'Dragon', 'Dragon', 'Steel', 'Ghost',
    'Water', 'Water', 'Bug', 'Rock', 'Dragon', 'Dragon', 'Grass', 'Bug', 'Bug',
    'Bug', 'Normal', 'Normal', 'Dark', 'Rock', 'Grass', 'Normal', 'Normal',
    'Fire', 'Ghost', 'Water', 'Normal', 'Water', 'Normal', 'Fighting', 'Water',
    'Psychic', 'Water', 'Rock', 'Water', 'Electric', 'Electric', 'Fighting',
    'Fighting', 'Fighting', 'Fire', 'Fire', 'Water', 'Fire', 'Fire',
    'Electric', 'Electric', 'Electric', 'Fighting', 'Dark', 'Ice', 'Water',
    'Dark', 'Electric', 'Fighting', 'Water', 'Water', 'Grass', 'Electric',
    'Water', 'Ground', 'Water', 'Bug', 'Steel', 'Fighting', 'Fighting',
    'Psychic', 'Psychic', 'Normal', 'Psychic', 'Steel', 'Steel', 'Bug',
    'Psychic', 'Psychic', 'Fighting', 'Fighting', 'Dark', 'Water', 'Normal',
    'Psychic', 'Normal', 'Electric', 'Ghost', 'Ghost', 'Fire', 'Fire', 'Bug',
    'Psychic', 'Water', 'Poison', 'Normal', 'Psychic', 'Dark', 'Psychic',
    'Psychic', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison',
    'Bug', 'Fire', 'Bug', 'Normal', 'Flying', 'Flying', 'Rock', 'Fire',
    'Grass', 'Water', 'Grass', 'Rock', 'Rock', 'Rock', 'Water', 'Electric',
    'Water', 'Water', 'Fighting', 'Fighting', 'Water', 'Grass', 'Fire', 'Bug',
    'Bug', 'Normal', 'Dark', 'Water', 'Normal', 'Grass', 'Ground', 'Ghost',
    'Water', 'Electric', 'Normal', 'Normal', 'Normal', 'Normal', 'Fire',
    'Electric', 'Ice', 'Bug', 'Bug', 'Water', 'Electric', 'Water', 'Water',
    'Water', 'Water', 'Fire', 'Dark', 'Normal', 'Normal', 'Normal', 'Fighting',
    'Water', 'Rock', 'Water', 'Rock', 'Dark', 'Normal', 'Fire', 'Water',
    'Fire', 'Grass', 'Water', 'Electric', 'Electric', 'Psychic', 'Rock',
    'Fire', 'Normal', 'Normal', 'Dragon', 'Ice', 'Normal', 'Rock', 'Steel',
    'Water', 'Water', 'Dragon', 'Psychic', 'Ground', 'Ground', 'Ground',
    'Fighting', 'Rock', 'Grass', 'Grass', 'Electric', 'Electric', 'Electric',
    'Electric', 'Electric', 'Electric', 'Normal', 'Dark', 'Dragon', 'Water',
    'Ground', 'Ground', 'Ground', 'Fighting', 'Normal', 'Bug', 'Grass', 'Bug',
    'Bug', 'Dark', 'Dark', 'Bug', 'Water', 'Water', 'Ice', 'Grass', 'Water',
    'Water', 'Normal', 'Grass', 'Grass', 'Poison', 'Bug', 'Water', 'Bug',
    'Dragon', 'Water', 'Water', 'Bug', 'Rock', 'Grass', 'Electric', 'Grass',
    'Bug', 'Ghost', 'Psychic', 'Bug', 'Water', 'Grass', 'Fire', 'Steel',
    'Grass', 'Grass', 'Normal', 'Poison', 'Poison', 'Poison', 'Normal',
    'Normal', 'Dragon', 'Water', 'Water', 'Water', 'Fire', 'Fairy', 'Normal',
    'Ice', 'Dark', 'Grass', 'Normal', 'Ice', 'Grass', 'Fairy', 'Psychic',
    'Rock', 'Normal', 'Bug', 'Ice', 'Bug', 'Normal', 'Ghost', 'Psychic',
    'Fairy', 'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Water', 'Water',
    'Steel', 'Normal', 'Ground', 'Poison', 'Rock', 'Water', 'Grass', 'Grass',
    'Bug', 'Normal', 'Bug', 'Poison', 'Water', 'Water', 'Normal', 'Ice',
    'Fairy', 'Psychic', 'Fairy', 'Normal', 'Fire', 'Grass', 'Grass', 'Normal',
    'Normal', 'Water', 'Water', 'Fire', 'Rock', 'Fighting', 'Fighting',
    'Water', 'Fairy', 'Fairy', 'Fairy', 'Fire', 'Fire', 'Grass', 'Water',
    'Poison', 'Normal', 'Ground', 'Grass', 'Ghost', 'Grass', 'Poison', 'Grass',
    'Water', 'Electric', 'Fire', 'Rock', 'Rock', 'Fighting', 'Rock', 'Dark',
    'Normal', 'Psychic', 'Normal', 'Psychic', 'Ice', 'Ice', 'Ice', 'Water',
    'Bug', 'Bug', 'Bug', 'Grass', 'Bug', 'Ground', 'Psychic', 'Grass',
    'Normal', 'Grass', 'Grass', 'Bug', 'Bug', 'Fire', 'Bug', 'Electric',
    'Dark', 'Fire', 'Water', 'Water', 'Ice', 'Water', 'Normal', 'Dark', 'Bug',
    'Grass', 'Poison', 'Grass', 'Bug', 'Water', 'Normal', 'Normal', 'Water',
    'Psychic', 'Psychic', 'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Psychic',
    'Psychic', 'Fairy', 'Ghost', 'Bug', 'Bug', 'Dark', 'Normal', 'Electric',
    'Electric', 'Dragon', 'Normal', 'Dark', 'Dark', 'Poison', 'Dark'
]

secondary_types = [
    'Ice', nan, nan, nan, 'Flying', 'Rock', nan, nan, nan, 'Flying', 'Ice',
    nan, 'Poison', nan, 'Bug', nan, nan, nan, 'Flying', 'Flying', 'Poison',
    'Bug', nan, 'Rock', 'Flying', nan, 'Ice', nan, nan, nan, 'Fairy', 'Fairy',
    nan, 'Psychic', nan, 'Water', 'Ground', nan, 'Steel', nan, nan, 'Flying',
    'Poison', nan, 'Psychic', nan, 'Poison', nan, 'Water', nan, 'Water',
    'Steel', nan, 'Fighting', nan, nan, nan, nan, nan, nan, 'Flying',
    'Fighting', 'Psychic', 'Psychic', 'Poison', nan, 'Poison', nan, nan, nan,
    'Flying', nan, 'Dark', 'Ground', 'Fairy', nan, 'Rock', 'Dark', nan, nan,
    nan, 'Grass', 'Fire', nan, 'Flying', nan, nan, 'Flying', nan, nan,
    'Fighting', nan, nan, nan, nan, 'Electric', nan, nan, nan, nan, nan,
    'Psychic', nan, nan, nan, 'Ice', 'Fighting', nan, 'Flying', 'Fighting',
    nan, nan, 'Rock', 'Fairy', 'Grass', nan, 'Dark', nan, 'Fighting', 'Flying',
    nan, 'Rock', nan, nan, nan, nan, nan, nan, 'Psychic', nan, 'Fairy',
    'Grass', 'Dragon', nan, 'Flying', 'Psychic', 'Ice', nan, 'Dragon', 'Fairy',
    'Ground', nan, nan, 'Flying', 'Flying', nan, 'Ghost', 'Dragon', nan,
    'Flying', 'Dark', nan, 'Flying', 'Flying', nan, nan, nan, 'Flying', nan,
    nan, nan, 'Steel', nan, nan, nan, 'Poison', 'Rock', nan, nan, nan, nan,
    nan, nan, nan, nan, nan, nan, 'Fighting', 'Flying', 'Steel', nan, 'Steel',
    nan, nan, 'Steel', 'Psychic', 'Psychic', nan, 'Flying', 'Flying', nan, nan,
    nan, 'Steel', 'Steel', nan, nan, nan, nan, 'Flying', 'Flying', nan, nan,
    nan, 'Dragon', 'Poison', 'Steel', nan, 'Ghost', nan, nan, 'Ghost', nan,
    nan, 'Ground', 'Fighting', 'Electric', nan, 'Ground', 'Fairy', 'Poison',
    'Ground', 'Steel', 'Poison', 'Ground', 'Ground', nan, 'Psychic', nan, nan,
    nan, 'Flying', 'Flying', 'Poison', nan, 'Flying', nan, nan, 'Ground',
    'Ghost', 'Ghost', nan, nan, nan, nan, nan, nan, nan, 'Ground', 'Dark', nan,
    nan, nan, 'Fire', nan, nan, nan, nan, nan, 'Flying', nan, nan, 'Poison',
    'Flying', nan, nan, 'Steel', 'Normal', 'Normal', 'Fighting', nan, nan, nan,
    nan, nan, nan, 'Flying', 'Flying', 'Ghost', 'Flying', 'Flying', nan,
    'Fire', 'Fire', nan, 'Dragon', nan, 'Fairy', nan, 'Fighting', 'Psychic',
    'Poison', 'Ghost', 'Fairy', 'Psychic', nan, 'Electric', 'Flying',
    'Psychic', 'Water', 'Water', nan, 'Poison', nan, nan, nan, 'Dragon', nan,
    'Fairy', nan, 'Fairy', nan, nan, nan, nan, nan, nan, 'Dark', 'Dark', nan,
    nan, 'Ice', 'Ice', 'Ice', 'Rock', 'Fire', 'Electric', 'Ice', 'Fire',
    'Ground', 'Psychic', 'Psychic', nan, 'Grass', 'Flying', 'Flying', nan, nan,
    nan, 'Grass', nan, nan, nan, 'Normal', 'Fire', 'Grass', nan, 'Grass', nan,
    'Steel', 'Grass', 'Flying', nan, 'Psychic', nan, nan, nan, nan, nan, nan,
    nan, 'Rock', nan, nan, nan, 'Steel', 'Steel', 'Steel', nan, 'Psychic',
    'Ground', nan, 'Flying', nan, nan, 'Flying', 'Flying', nan, nan, 'Fairy',
    nan, 'Ground', 'Flying', 'Fairy', 'Psychic', 'Psychic', nan, nan, nan, nan,
    'Psychic', 'Psychic', nan, nan, nan, nan, nan, nan, nan, nan, 'Fairy', nan,
    nan, nan, nan, 'Flying', 'Fighting', 'Flying', 'Fairy', nan, nan, nan, nan,
    'Flying', nan, 'Flying', 'Ground', 'Ground', nan, nan, nan, nan, 'Ground',
    nan, 'Flying', 'Flying', 'Dragon', 'Dragon', nan, 'Ground', 'Dark', nan,
    'Poison', 'Water', 'Water', 'Ground', nan, nan, 'Dragon', 'Ground', nan,
    'Dark', nan, nan, nan, 'Grass', 'Grass', nan, 'Steel', 'Flying', nan, nan,
    nan, 'Grass', nan, nan, 'Flying', 'Flying', 'Flying', 'Flying', 'Fighting',
    nan, 'Ground', nan, nan, nan, nan, nan, nan, nan, 'Fighting', nan, nan,
    nan, nan, nan, nan, nan, 'Steel', nan, 'Ground', nan, nan, 'Normal',
    'Ground', nan, nan, 'Poison', nan, nan, 'Fairy', nan, nan, nan, nan,
    'Flying', nan, nan, nan, nan, 'Rock', nan, 'Fire', nan, 'Rock', 'Rock',
    'Rock', nan, nan, 'Poison', 'Poison', 'Ghost', 'Flying', 'Ice', 'Fire',
    'Grass', 'Water', 'Flying', 'Ghost', 'Flying', nan, 'Dark', nan, nan, nan,
    'Grass', nan, nan, 'Steel', 'Poison', 'Fighting', 'Fighting', 'Flying',
    nan, nan, 'Water', nan, nan, 'Ground', nan, nan, nan, nan, 'Grass', 'Dark',
    'Ghost', nan, nan, nan, nan, 'Steel', 'Dark', nan, nan, 'Rock', nan,
    'Flying', nan, nan, nan, nan, 'Flying', nan, 'Flying', nan, 'Bug', 'Water',
    'Dark', nan, nan, nan, 'Psychic', 'Psychic', 'Psychic', nan, nan, nan,
    'Psychic', 'Ice', nan, nan, nan, 'Ice', nan, nan, 'Psychic', 'Flying', nan,
    'Water', 'Poison', nan, 'Dark', nan, nan, nan, nan, 'Flying', 'Flying',
    'Flying', 'Psychic', nan, 'Ground', nan, 'Electric', 'Dark', nan, nan, nan,
    nan, 'Water', 'Flying', 'Grass', nan, 'Ground', 'Flying', 'Flying',
    'Ground', nan, 'Flying', nan, 'Flying', 'Flying', nan, nan, nan, nan,
    'Poison', 'Poison', nan, 'Fighting', nan, nan, 'Rock', 'Flying', nan,
    'Flying', nan, nan, 'Ground', nan, 'Fighting', 'Flying', nan, nan, 'Grass',
    'Flying', nan, nan, nan, nan, nan, 'Dark', 'Dragon', nan, 'Dragon', nan,
    'Flying', nan, nan, nan, nan, nan, nan, nan, 'Poison', 'Poison', 'Poison',
    'Poison', 'Flying', 'Dragon', 'Fire', 'Poison', nan, 'Poison', 'Fighting',
    'Flying', nan, 'Water', 'Fire', nan, 'Flying', nan, nan, nan, 'Water', nan,
    nan, 'Ice', 'Poison', 'Poison', nan, 'Fairy', 'Poison', 'Ground', nan,
    'Fairy', 'Flying', nan, 'Flying', 'Ground', 'Grass', 'Ground', 'Steel',
    nan, nan, 'Flying', nan, nan, 'Flying', 'Flying', 'Flying', nan, 'Flying',
    nan, 'Electric', nan, nan, nan, 'Flying', 'Dragon'
]

# We want to combine each Pokémon's name and types together so that you easily see a description of each Pokémon.
# Practice using zip() to accomplish this task.

# The zip() function takes iterables (can be zero or more), aggregates them in a tuple, and returns it.
# languages = ['Java', 'Python', 'JavaScript']
# versions = [14, 3, 6]

# result = zip(languages, versions)
# print(list(result))

# Output: [('Java', 14), ('Python', 3), ('JavaScript', 6)]

# Combine the names list and the primary_types list into a new list object (called names_type1).

# Combine names, primary_types, and secondary_types (in that order) using zip() and unpack the zip object into a new list.

# Use zip() to combine the first five items from the names list and the first three items from the primary_types list.
